Learning_Journal/Core_things/views.py
"""This is my views file for Core_things.
   It contains the main/home, views/pages for
   My app.
"""

from flask import Flask, render_template, Blueprint
from Learning_Journal.models import Journal_Entry

# Blueprint creation
core_blueprint = Blueprint('core_blueprint', __name__)


# Home page creation
@core_blueprint.route('/')
def index_page():
    return render_template("home.html")


# Entries page creation
@core_blueprint.route('/entries')
def list_page():
    """ This view collects all of the journal entries
        In the Database, then it displays them on the
        entries page.
    """
    journals = Journal_Entry.query.all()
    return render_template("index.html", journals = journals)

Learning_Journal/Journals/views.py
"""This is my views file for Journals.
   It contains the ability to, create, read, update and delete,
   for my app.
"""

from Learning_Journal import db
from Learning_Journal.models import Journal_Entry
from Learning_Journal.Journals.forms import JournalForm
from Learning_Journal.models import Journal_Entry, User
from flask_login import login_required, current_user

from flask import Blueprint, redirect, render_template, url_for


journal_blueprint = Blueprint('journal_blueprint', __name__)


#read
@journal_blueprint.route("/details/<int:journal_post_id>")
@login_required
def details(journal_post_id):
    """This is my read view. It sends all of the journal entries into a variable list
       Then it send the list to the details template.
    """

    entry = Journal_Entry.query.filter_by(id=journal_post_id)

    return render_template("detail.html", entry=entry)



#create
@journal_blueprint.route("/entry", methods=["GET", "POST"])
@login_required
def add():
    """This is my add view. It adds new entries into the database after
       The user has completed the form on the new.html template.
    """
    form = JournalForm()

    if form.validate_on_submit():
        new_journal = Journal_Entry(title=form.title.data,
                                    date=form.date.data,
                                    time_spent=form.time_spent.data,
                                    what_i_learned=form.what_i_learned.data,
                                    resources_to_remember=form.resources_to_remember.data,
                                    owner_id=current_user.id)

        db.session.add(new_journal)
        db.session.commit()

        return redirect(url_for("core_blueprint.index_page"))

    else:
        print("FORM ERRORS: \n", form.errors)

    return render_template("new.html", form=form)






@journal_blueprint.route("/entries/edit/<int:journal_post_id>", methods = ["GET", "POST"])
@login_required
def update(journal_post_id):
    """This is my journal update view. Once the form is completed on the template page
       The view looks for the entry that matches the same ID. Once it has a match,
       It begins putting new values into that entries coloumns.
    """
    form = JournalForm()
    entry = Journal_Entry.query.filter_by(id=journal_post_id).first()
    if entry.owner_id == current_user.id:

        if form.validate_on_submit():
            entry.title = form.title.data
            entry.date = form.date.data
            entry.time_spent = form.time_spent.data
            entry.what_i_learned = form.what_i_learned.data
            entry.resources_to_remember = form.resources_to_remember.data
            entry.owner_id = current_user.id

            db.session.add(entry)
            db.session.commit()

            return redirect(url_for("core_blueprint.index_page"))
    else:
        return redirect(url_for("core_blueprint.index_page"))

    return render_template("edit.html", form = form)


@journal_blueprint.route("/entries/delete/<int:journal_post_id>", methods=["GET", "POST"])
@login_required
def delete_post(journal_post_id):
    """This is my delete view. Just like the update view, it takes the ID of the,
       entry that the user is trying to delete on the details view/page.
       It then matches the ID to the entry in the database. Once a match is found,
       a deletion occurs and then the user is redirected to the index page.
    """
    entry = Journal_Entry.query.filter_by(id=journal_post_id).first()

    if entry.owner_id != current_user.id:
        return redirect(url_for("core_blueprint.index_page"))

    db.session.delete(entry)
    db.session.commit()

    return redirect(url_for("core_blueprint.index_page"))

Learning_Journal/Users/views.py
from Learning_Journal import db
from Learning_Journal.models import User
from Learning_Journal.Users.forms import LoginForm, RegistrationForm

from flask_login import login_required, login_user, logout_user
from flask import render_template, redirect, url_for, Blueprint


users_blueprint = Blueprint('users_blueprint', __name__)


@users_blueprint.route('/register', methods=["GET", "POST"])
def register():
    """This is the register view. It creates a new User to input into the database"""

    form = RegistrationForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:

            addition = User(name=form.name.data,
                            email=form.email.data,
                            password=form.password.data)

            db.session.add(addition)
            db.session.commit()

            return redirect(url_for("users_blueprint.login"))

    return render_template("register.html", form=form)


@users_blueprint.route('/login', methods=["GET", "POST"])
def login():
    """This is the login view. It allows the user to log in, it checks
       the email the user has provided, against the emails in the database.
       If there is a match, the user is logged in, and is able to make a post
    """
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:
            login_user(user)

            return redirect(url_for("core_blueprint.index_page"))

    return render_template("login.html", form=form)


@users_blueprint.route("/logout")
@login_required
def logout():
    """This is the logout function. If the user clicks on logout in the navigation bar,
       the user loses the rights to create a post.
    """
    logout_user()
    return redirect(url_for("core_blueprint.index_page"))

Learning_Journal/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Cousine:400" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:600" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="/static/normalize.css">
    <link rel="stylesheet" href="/static/site.css">
    <title>Title</title>
</head>
<body>

    <ul>
        <li class=""><a href="{{ url_for("core_blueprint.index_page") }}">Home</a></li>
        <li class=""><a href="{{ url_for("core_blueprint.list_page") }}">Entries</a></li>
        {% if current_user.is_authenticated %}

        <li><a href="{{ url_for("users_blueprint.logout") }}">Logout</a></li>

        <li><a href="{{ url_for("journal_blueprint.add") }}">Make Entry</a></li>
        {%  else %}

        <li><a href="{{ url_for("users_blueprint.login") }}">Login</a></li>
        <li><a href="{{ url_for("users_blueprint.register") }}">Register</a></li>

        {% endif %}


    </ul>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

Learning_Journal/templates/detail.html
{%  extends "base.html" %}

{% block content %}

        <header>
            <div class="container">
                <div class="site-header">
                    <a class="logo" href="{{ url_for("journal_blueprint.add") }}"><i class="material-icons">library_books</i></a>
                    <a class="button icon-right" href="{{ url_for("journal_blueprint.add") }}"><span>New Entry</span> <i class="material-icons">add</i></a>
                </div>
            </div>
        </header>
        <section>
            <div class="container">
                <div class="entry-list single">
                    {% for thing in entry %}
                        <article>
                        <h1> Entry ID:{{ thing.id }}</h1>
                        <h1>{{ thing.title }}</h1>
                        <time>{{ thing.date }}</time>
                        <div class="entry">
                            <h3>Time Spent: </h3>
                            <p>{{ thing.time_spent }}</p>
                        </div>
                        <div class="entry">
                            <h3>What I Learned:</h3>
                            <p>{{ thing.what_i_learned }}</p>
                        </div>
                        <div class="entry">
                            <h3>Resources to Remember:</h3>
                            <ul>
                                <li><a href="">{{ thing.resources_to_remember }}</a></li>

                            </ul>
                        </div>
                    </article>
                    <div class="edit">
                        <p><a href="{{ url_for("journal_blueprint.update", journal_post_id=thing.id) }}">Edit Entry</a></p>
                        <p><a href="{{ url_for("journal_blueprint.delete_post", journal_post_id=thing.id) }}">Delete</a></p>
                    </div>
                    {% endfor %}


                </div>
            </div>

        </section>
        <footer>
            <div>
                &copy; MyJournal
            </div>
        </footer>

{% endblock %}

Learning_Journal/templates/edit.html
{% extends "base.html" %}

{% block content %}



        <header>
            <div class="container">
                <div class="site-header">
                    <a class="logo" href="{{ url_for("journal_blueprint.add") }}"><i class="material-icons">library_books</i></a>
                    <a class="button icon-right" href="{{ url_for("journal_blueprint.add") }}"><span>New Entry</span> <i class="material-icons">add</i></a>
                </div>
            </div>
        </header>
        <section>
            <div class="container">
                <div class="edit-entry">
                    <h2>Edit Entry</h2>
                    <form method = "POST">
                        {{ form.hidden_tag() }}
                        {{ form.title.label }}{{ form.title }}
                        {{ form.date.label }}{{ form.date }}
                        {{ form.time_spent.label }}{{ form.time_spent }}
                        {{ form.what_i_learned.label }}{{ form.what_i_learned }}
                        {{ form.resources_to_remember.label }}{{ form.resources_to_remember }}
                        <input type="submit" value="Publish Entry" class="button">
                        <a href="{{ url_for("core_blueprint.index_page")}}" class="button button-secondary">Cancel</a>
                    </form>
                </div>
            </div>
        </section>
        <footer>
            <div>
                &copy; MyJournal
            </div>
        </footer>

{% endblock %}

Learning_Journal/templates/home.html
{% extends "base.html" %}

{% block content %}
    {% if current_user.is_authenticated %}
    <h1>Welcome {{ current_user.name }}. Please make a Post!</h1>

    {% else %}
    <h1> Hi and Welcome! Please log in to create/delete/edit a post.</h1>

    {% endif %}

{% endblock %}

Learning_Journal/templates/index.html
{% extends "base.html" %}
{% block content %}


            <div class="container">
                <div class="site-header">
                    <a class="logo" href="{{ url_for("journal_blueprint.add") }}"><i class="material-icons">library_books</i></a>
                    <a class="button icon-right" href="{{ url_for("journal_blueprint.add") }}"><span>New Entry</span> <i class="material-icons">add</i></a>
                </div>
            </div>
        </header>
        <section>
            <div class="container">
                <div class="entry-list">
                    {% for thing in journals %}

                    <article>
                        <h2><a href="{{ url_for("journal_blueprint.details", journal_post_id=thing.id) }}">{{ thing.title }}</a></h2>
                        <time >{{ thing.date }}</time>
                    </article>

                    {% endfor %}

                </div>
            </div>
        </section>
        <footer>
            <div>
                &copy; MyJournal
            </div>
        </footer>
{% endblock %}

Learning_Journal/templates/login.html
{% extends "base.html" %}


{% block content %}
    <form method="POST">
        {{ form.hidden_tag() }}
        {{ form.email.label }} {{ form.email }}<br>
        {{ form.password.label }} {{ form.password }}<br>
        {{ form.submit }}


    </form>

{% endblock %}

Learning_Journal/templates/new.html
{% extends "base.html" %}

{% block content %}
        <header>
            <div class="container">
                <div class="site-header">
                    <a class="logo" href="{{ url_for("journal_blueprint.add") }}"><i class="material-icons">library_books</i></a>
                    <a class="button icon-right" href="{{ url_for("journal_blueprint.add") }}"><span>New Entry</span> <i class="material-icons">add</i></a>
                </div>
            </div>
        </header>
        <section>
            <div class="container">
                <div class="new-entry">
                    <h2>New Entry</h2>
                    <form method="POST">

                        {{ form.hidden_tag() }}
                        {{ form.title.label }}{{ form.title }}

                        <p>{{ form.date.label }} YYYY-MM-DD</p>{{ form.date }}
                        {{ form.time_spent.label }}{{ form.time_spent }}
                        {{ form.what_i_learned.label }}{{ form.what_i_learned }}
                        {{ form.resources_to_remember.label }}{{ form.resources_to_remember }}
                        {{ form.submit }}

                    </form>
                </div>
            </div>
        </section>
        <footer>
            <div>
                &copy; MyJournal
            </div>
        </footer>
{% endblock %}

Learning_Journal/templates/register.html
{% extends "base.html" %}

{% block content %}
    <h1>Please Register!</h1>
    <form method="POST">
        {{ form.hidden_tag() }}
        {{ form.name.label }} {{ form.name }}<br>
        {{ form.email.label }} {{ form.email }}<br>
        {{ form.password.label }} {{ form.password }}<br>
        {{ form.password_confirm.label }} {{ form.password_confirm }}<br>
        {{ form.submit }}

    </form>
{% endblock %}